services:
  master:
    build:
      context: .
      dockerfile: ./master/context/Dockerfile
      args:
        IPADDR: 172.24.0.10
        NETMASK: 255.255.0.0
        SERVICE: master
    networks:
      bind:
        ipv4_address: 172.24.0.10
    volumes:
      - ./master/code:/code
    hostname: master.example.com
    privileged: true
    cap_add:
      - NET_ADMIN

  slave:
    build:
      context: .
      dockerfile: ./slave/context/Dockerfile
      args:
        IPADDR: 172.24.0.41
        NETMASK: 255.255.0.0
        SERVICE: slave
    networks:
      bind:
        ipv4_address: 172.24.0.41
    volumes:
      - ./slave/code:/code
    hostname: slave.example.com
    tty: true
    cap_add:
      - NET_ADMIN

  client:
    build:
      context: .
      dockerfile: ./client/context/Dockerfile
      args:
        IPADDR: 172.24.0.11
        NETMASK: 255.255.0.0
        SERVICE: client
    networks:
      bind:
        ipv4_address: 172.24.0.11
    volumes:
      - ./client/code:/code
    hostname: client.example.com
    tty: true
    cap_add:
      - NET_ADMIN

networks:
  bind:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/16
          gateway: 172.24.0.1
